"""users table

Revision ID: 774032277e62
Revises: 8ca9cf4dda7c
Create Date: 2018-02-11 12:24:28.591485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774032277e62'
down_revision = '8ca9cf4dda7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('sharedProfileId', sa.String(length=120), nullable=False),
    sa.Column('urls', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sharedProfileId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('fb', sa.String(length=80), nullable=True),
    sa.Column('ig', sa.String(length=80), nullable=True),
    sa.Column('mail', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('shared_profile')
    # ### end Alembic commands ###
