"""users table

Revision ID: 8ca9cf4dda7c
Revises: b3cbdad86310
Create Date: 2018-02-11 12:23:40.494432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca9cf4dda7c'
down_revision = 'b3cbdad86310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_profile')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('fb', sa.VARCHAR(length=80), nullable=True),
    sa.Column('ig', sa.VARCHAR(length=80), nullable=True),
    sa.Column('mail', sa.VARCHAR(length=80), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('shared_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('sharedProfileId', sa.VARCHAR(length=120), nullable=False),
    sa.Column('urls', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sharedProfileId'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
